# Generated by Django 5.1.1 on 2024-09-09 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electricitydata',
            unique_together={('region', 'date', 'time_start')},
        ),
        migrations.AlterUniqueTogether(
            name='weatherdata',
            unique_together={('city', 'date', 'time_start')},
        ),
    ]
